/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SistemInformasiRouteImport } from './routes/sistem-informasi'
import { Route as PelaporanRouteImport } from './routes/pelaporan'
import { Route as KonsultasiMutuRouteImport } from './routes/konsultasi-mutu'
import { Route as Index1RouteImport } from './routes/index1'
import { Route as AdminkontenRouteImport } from './routes/_adminkonten'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TentangVisiMisiRouteImport } from './routes/tentang/visi-misi'
import { Route as TentangTupoksiRouteImport } from './routes/tentang/tupoksi'
import { Route as TentangSambutanRektorRouteImport } from './routes/tentang/sambutan-rektor'
import { Route as TentangOrganisasiRouteImport } from './routes/tentang/organisasi'
import { Route as SpmeSpmeRouteImport } from './routes/spme/spme'
import { Route as InformasiDetailBeritaRouteImport } from './routes/informasi/detail-berita'
import { Route as InformasiBeritaRouteImport } from './routes/informasi/berita'
import { Route as EvaluasiInstrumenRouteImport } from './routes/evaluasi/instrumen'
import { Route as DokumenSpmiRouteImport } from './routes/dokumen/spmi'
import { Route as DokumenPustakaRouteImport } from './routes/dokumen/pustaka'
import { Route as DokumenPeraturanUudRouteImport } from './routes/dokumen/peraturan-uud'
import { Route as AdminkontenAdminKontenIndexRouteImport } from './routes/_adminkonten/admin-konten/index'
import { Route as AdminkontenAdminKontenSistemInformasiRouteImport } from './routes/_adminkonten/admin-konten/sistem-informasi'
import { Route as AdminkontenAdminKontenPengaturanRouteImport } from './routes/_adminkonten/admin-konten/pengaturan'
import { Route as AdminkontenAdminKontenPelaporanRouteImport } from './routes/_adminkonten/admin-konten/pelaporan'
import { Route as AdminkontenAdminKontenKonsultasiMutuRouteImport } from './routes/_adminkonten/admin-konten/konsultasi-mutu'
import { Route as AdminkontenAdminKontenKelolaMenuRouteImport } from './routes/_adminkonten/admin-konten/kelola-menu'
import { Route as AdminkontenAdminKontenBerandaRouteImport } from './routes/_adminkonten/admin-konten/beranda'
import { Route as AdminkontenAdminKontenTentangVisiMisiRouteImport } from './routes/_adminkonten/admin-konten/tentang/visi-misi'
import { Route as AdminkontenAdminKontenTentangTupoksiRouteImport } from './routes/_adminkonten/admin-konten/tentang/tupoksi'
import { Route as AdminkontenAdminKontenTentangSambutanRektorRouteImport } from './routes/_adminkonten/admin-konten/tentang/sambutan-rektor'
import { Route as AdminkontenAdminKontenTentangOrganisasiRouteImport } from './routes/_adminkonten/admin-konten/tentang/organisasi'
import { Route as AdminkontenAdminKontenSpmeSpmeRouteImport } from './routes/_adminkonten/admin-konten/spme/spme'
import { Route as AdminkontenAdminKontenInformasiPengumumanRouteImport } from './routes/_adminkonten/admin-konten/informasi/pengumuman'
import { Route as AdminkontenAdminKontenInformasiDetailBeritaRouteImport } from './routes/_adminkonten/admin-konten/informasi/detail-berita'
import { Route as AdminkontenAdminKontenInformasiBeritaRouteImport } from './routes/_adminkonten/admin-konten/informasi/berita'
import { Route as AdminkontenAdminKontenEvaluasiInstrumenRouteImport } from './routes/_adminkonten/admin-konten/evaluasi/instrumen'
import { Route as AdminkontenAdminKontenDokumenSpmiRouteImport } from './routes/_adminkonten/admin-konten/dokumen/spmi'
import { Route as AdminkontenAdminKontenDokumenPustakaRouteImport } from './routes/_adminkonten/admin-konten/dokumen/pustaka'
import { Route as AdminkontenAdminKontenDokumenPeraturanUudRouteImport } from './routes/_adminkonten/admin-konten/dokumen/peraturan-uud'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemInformasiRoute = SistemInformasiRouteImport.update({
  id: '/sistem-informasi',
  path: '/sistem-informasi',
  getParentRoute: () => rootRouteImport,
} as any)
const PelaporanRoute = PelaporanRouteImport.update({
  id: '/pelaporan',
  path: '/pelaporan',
  getParentRoute: () => rootRouteImport,
} as any)
const KonsultasiMutuRoute = KonsultasiMutuRouteImport.update({
  id: '/konsultasi-mutu',
  path: '/konsultasi-mutu',
  getParentRoute: () => rootRouteImport,
} as any)
const Index1Route = Index1RouteImport.update({
  id: '/index1',
  path: '/index1',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminkontenRoute = AdminkontenRouteImport.update({
  id: '/_adminkonten',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangVisiMisiRoute = TentangVisiMisiRouteImport.update({
  id: '/tentang/visi-misi',
  path: '/tentang/visi-misi',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangTupoksiRoute = TentangTupoksiRouteImport.update({
  id: '/tentang/tupoksi',
  path: '/tentang/tupoksi',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangSambutanRektorRoute = TentangSambutanRektorRouteImport.update({
  id: '/tentang/sambutan-rektor',
  path: '/tentang/sambutan-rektor',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangOrganisasiRoute = TentangOrganisasiRouteImport.update({
  id: '/tentang/organisasi',
  path: '/tentang/organisasi',
  getParentRoute: () => rootRouteImport,
} as any)
const SpmeSpmeRoute = SpmeSpmeRouteImport.update({
  id: '/spme/spme',
  path: '/spme/spme',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiDetailBeritaRoute = InformasiDetailBeritaRouteImport.update({
  id: '/informasi/detail-berita',
  path: '/informasi/detail-berita',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiBeritaRoute = InformasiBeritaRouteImport.update({
  id: '/informasi/berita',
  path: '/informasi/berita',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluasiInstrumenRoute = EvaluasiInstrumenRouteImport.update({
  id: '/evaluasi/instrumen',
  path: '/evaluasi/instrumen',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumenSpmiRoute = DokumenSpmiRouteImport.update({
  id: '/dokumen/spmi',
  path: '/dokumen/spmi',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumenPustakaRoute = DokumenPustakaRouteImport.update({
  id: '/dokumen/pustaka',
  path: '/dokumen/pustaka',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumenPeraturanUudRoute = DokumenPeraturanUudRouteImport.update({
  id: '/dokumen/peraturan-uud',
  path: '/dokumen/peraturan-uud',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminkontenAdminKontenIndexRoute =
  AdminkontenAdminKontenIndexRouteImport.update({
    id: '/admin-konten/',
    path: '/admin-konten/',
    getParentRoute: () => AdminkontenRoute,
  } as any)
const AdminkontenAdminKontenSistemInformasiRoute =
  AdminkontenAdminKontenSistemInformasiRouteImport.update({
    id: '/admin-konten/sistem-informasi',
    path: '/admin-konten/sistem-informasi',
    getParentRoute: () => AdminkontenRoute,
  } as any)
const AdminkontenAdminKontenPengaturanRoute =
  AdminkontenAdminKontenPengaturanRouteImport.update({
    id: '/admin-konten/pengaturan',
    path: '/admin-konten/pengaturan',
    getParentRoute: () => AdminkontenRoute,
  } as any)
const AdminkontenAdminKontenPelaporanRoute =
  AdminkontenAdminKontenPelaporanRouteImport.update({
    id: '/admin-konten/pelaporan',
    path: '/admin-konten/pelaporan',
    getParentRoute: () => AdminkontenRoute,
  } as any)
const AdminkontenAdminKontenKonsultasiMutuRoute =
  AdminkontenAdminKontenKonsultasiMutuRouteImport.update({
    id: '/admin-konten/konsultasi-mutu',
    path: '/admin-konten/konsultasi-mutu',
    getParentRoute: () => AdminkontenRoute,
  } as any)
const AdminkontenAdminKontenKelolaMenuRoute =
  AdminkontenAdminKontenKelolaMenuRouteImport.update({
    id: '/admin-konten/kelola-menu',
    path: '/admin-konten/kelola-menu',
    getParentRoute: () => AdminkontenRoute,
  } as any)
const AdminkontenAdminKontenBerandaRoute =
  AdminkontenAdminKontenBerandaRouteImport.update({
    id: '/admin-konten/beranda',
    path: '/admin-konten/beranda',
    getParentRoute: () => AdminkontenRoute,
  } as any)
const AdminkontenAdminKontenTentangVisiMisiRoute =
  AdminkontenAdminKontenTentangVisiMisiRouteImport.update({
    id: '/admin-konten/tentang/visi-misi',
    path: '/admin-konten/tentang/visi-misi',
    getParentRoute: () => AdminkontenRoute,
  } as any)
const AdminkontenAdminKontenTentangTupoksiRoute =
  AdminkontenAdminKontenTentangTupoksiRouteImport.update({
    id: '/admin-konten/tentang/tupoksi',
    path: '/admin-konten/tentang/tupoksi',
    getParentRoute: () => AdminkontenRoute,
  } as any)
const AdminkontenAdminKontenTentangSambutanRektorRoute =
  AdminkontenAdminKontenTentangSambutanRektorRouteImport.update({
    id: '/admin-konten/tentang/sambutan-rektor',
    path: '/admin-konten/tentang/sambutan-rektor',
    getParentRoute: () => AdminkontenRoute,
  } as any)
const AdminkontenAdminKontenTentangOrganisasiRoute =
  AdminkontenAdminKontenTentangOrganisasiRouteImport.update({
    id: '/admin-konten/tentang/organisasi',
    path: '/admin-konten/tentang/organisasi',
    getParentRoute: () => AdminkontenRoute,
  } as any)
const AdminkontenAdminKontenSpmeSpmeRoute =
  AdminkontenAdminKontenSpmeSpmeRouteImport.update({
    id: '/admin-konten/spme/spme',
    path: '/admin-konten/spme/spme',
    getParentRoute: () => AdminkontenRoute,
  } as any)
const AdminkontenAdminKontenInformasiPengumumanRoute =
  AdminkontenAdminKontenInformasiPengumumanRouteImport.update({
    id: '/admin-konten/informasi/pengumuman',
    path: '/admin-konten/informasi/pengumuman',
    getParentRoute: () => AdminkontenRoute,
  } as any)
const AdminkontenAdminKontenInformasiDetailBeritaRoute =
  AdminkontenAdminKontenInformasiDetailBeritaRouteImport.update({
    id: '/admin-konten/informasi/detail-berita',
    path: '/admin-konten/informasi/detail-berita',
    getParentRoute: () => AdminkontenRoute,
  } as any)
const AdminkontenAdminKontenInformasiBeritaRoute =
  AdminkontenAdminKontenInformasiBeritaRouteImport.update({
    id: '/admin-konten/informasi/berita',
    path: '/admin-konten/informasi/berita',
    getParentRoute: () => AdminkontenRoute,
  } as any)
const AdminkontenAdminKontenEvaluasiInstrumenRoute =
  AdminkontenAdminKontenEvaluasiInstrumenRouteImport.update({
    id: '/admin-konten/evaluasi/instrumen',
    path: '/admin-konten/evaluasi/instrumen',
    getParentRoute: () => AdminkontenRoute,
  } as any)
const AdminkontenAdminKontenDokumenSpmiRoute =
  AdminkontenAdminKontenDokumenSpmiRouteImport.update({
    id: '/admin-konten/dokumen/spmi',
    path: '/admin-konten/dokumen/spmi',
    getParentRoute: () => AdminkontenRoute,
  } as any)
const AdminkontenAdminKontenDokumenPustakaRoute =
  AdminkontenAdminKontenDokumenPustakaRouteImport.update({
    id: '/admin-konten/dokumen/pustaka',
    path: '/admin-konten/dokumen/pustaka',
    getParentRoute: () => AdminkontenRoute,
  } as any)
const AdminkontenAdminKontenDokumenPeraturanUudRoute =
  AdminkontenAdminKontenDokumenPeraturanUudRouteImport.update({
    id: '/admin-konten/dokumen/peraturan-uud',
    path: '/admin-konten/dokumen/peraturan-uud',
    getParentRoute: () => AdminkontenRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/index1': typeof Index1Route
  '/konsultasi-mutu': typeof KonsultasiMutuRoute
  '/pelaporan': typeof PelaporanRoute
  '/sistem-informasi': typeof SistemInformasiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dokumen/peraturan-uud': typeof DokumenPeraturanUudRoute
  '/dokumen/pustaka': typeof DokumenPustakaRoute
  '/dokumen/spmi': typeof DokumenSpmiRoute
  '/evaluasi/instrumen': typeof EvaluasiInstrumenRoute
  '/informasi/berita': typeof InformasiBeritaRoute
  '/informasi/detail-berita': typeof InformasiDetailBeritaRoute
  '/spme/spme': typeof SpmeSpmeRoute
  '/tentang/organisasi': typeof TentangOrganisasiRoute
  '/tentang/sambutan-rektor': typeof TentangSambutanRektorRoute
  '/tentang/tupoksi': typeof TentangTupoksiRoute
  '/tentang/visi-misi': typeof TentangVisiMisiRoute
  '/admin-konten/beranda': typeof AdminkontenAdminKontenBerandaRoute
  '/admin-konten/kelola-menu': typeof AdminkontenAdminKontenKelolaMenuRoute
  '/admin-konten/konsultasi-mutu': typeof AdminkontenAdminKontenKonsultasiMutuRoute
  '/admin-konten/pelaporan': typeof AdminkontenAdminKontenPelaporanRoute
  '/admin-konten/pengaturan': typeof AdminkontenAdminKontenPengaturanRoute
  '/admin-konten/sistem-informasi': typeof AdminkontenAdminKontenSistemInformasiRoute
  '/admin-konten/': typeof AdminkontenAdminKontenIndexRoute
  '/admin-konten/dokumen/peraturan-uud': typeof AdminkontenAdminKontenDokumenPeraturanUudRoute
  '/admin-konten/dokumen/pustaka': typeof AdminkontenAdminKontenDokumenPustakaRoute
  '/admin-konten/dokumen/spmi': typeof AdminkontenAdminKontenDokumenSpmiRoute
  '/admin-konten/evaluasi/instrumen': typeof AdminkontenAdminKontenEvaluasiInstrumenRoute
  '/admin-konten/informasi/berita': typeof AdminkontenAdminKontenInformasiBeritaRoute
  '/admin-konten/informasi/detail-berita': typeof AdminkontenAdminKontenInformasiDetailBeritaRoute
  '/admin-konten/informasi/pengumuman': typeof AdminkontenAdminKontenInformasiPengumumanRoute
  '/admin-konten/spme/spme': typeof AdminkontenAdminKontenSpmeSpmeRoute
  '/admin-konten/tentang/organisasi': typeof AdminkontenAdminKontenTentangOrganisasiRoute
  '/admin-konten/tentang/sambutan-rektor': typeof AdminkontenAdminKontenTentangSambutanRektorRoute
  '/admin-konten/tentang/tupoksi': typeof AdminkontenAdminKontenTentangTupoksiRoute
  '/admin-konten/tentang/visi-misi': typeof AdminkontenAdminKontenTentangVisiMisiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/index1': typeof Index1Route
  '/konsultasi-mutu': typeof KonsultasiMutuRoute
  '/pelaporan': typeof PelaporanRoute
  '/sistem-informasi': typeof SistemInformasiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dokumen/peraturan-uud': typeof DokumenPeraturanUudRoute
  '/dokumen/pustaka': typeof DokumenPustakaRoute
  '/dokumen/spmi': typeof DokumenSpmiRoute
  '/evaluasi/instrumen': typeof EvaluasiInstrumenRoute
  '/informasi/berita': typeof InformasiBeritaRoute
  '/informasi/detail-berita': typeof InformasiDetailBeritaRoute
  '/spme/spme': typeof SpmeSpmeRoute
  '/tentang/organisasi': typeof TentangOrganisasiRoute
  '/tentang/sambutan-rektor': typeof TentangSambutanRektorRoute
  '/tentang/tupoksi': typeof TentangTupoksiRoute
  '/tentang/visi-misi': typeof TentangVisiMisiRoute
  '/admin-konten/beranda': typeof AdminkontenAdminKontenBerandaRoute
  '/admin-konten/kelola-menu': typeof AdminkontenAdminKontenKelolaMenuRoute
  '/admin-konten/konsultasi-mutu': typeof AdminkontenAdminKontenKonsultasiMutuRoute
  '/admin-konten/pelaporan': typeof AdminkontenAdminKontenPelaporanRoute
  '/admin-konten/pengaturan': typeof AdminkontenAdminKontenPengaturanRoute
  '/admin-konten/sistem-informasi': typeof AdminkontenAdminKontenSistemInformasiRoute
  '/admin-konten': typeof AdminkontenAdminKontenIndexRoute
  '/admin-konten/dokumen/peraturan-uud': typeof AdminkontenAdminKontenDokumenPeraturanUudRoute
  '/admin-konten/dokumen/pustaka': typeof AdminkontenAdminKontenDokumenPustakaRoute
  '/admin-konten/dokumen/spmi': typeof AdminkontenAdminKontenDokumenSpmiRoute
  '/admin-konten/evaluasi/instrumen': typeof AdminkontenAdminKontenEvaluasiInstrumenRoute
  '/admin-konten/informasi/berita': typeof AdminkontenAdminKontenInformasiBeritaRoute
  '/admin-konten/informasi/detail-berita': typeof AdminkontenAdminKontenInformasiDetailBeritaRoute
  '/admin-konten/informasi/pengumuman': typeof AdminkontenAdminKontenInformasiPengumumanRoute
  '/admin-konten/spme/spme': typeof AdminkontenAdminKontenSpmeSpmeRoute
  '/admin-konten/tentang/organisasi': typeof AdminkontenAdminKontenTentangOrganisasiRoute
  '/admin-konten/tentang/sambutan-rektor': typeof AdminkontenAdminKontenTentangSambutanRektorRoute
  '/admin-konten/tentang/tupoksi': typeof AdminkontenAdminKontenTentangTupoksiRoute
  '/admin-konten/tentang/visi-misi': typeof AdminkontenAdminKontenTentangVisiMisiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_adminkonten': typeof AdminkontenRouteWithChildren
  '/index1': typeof Index1Route
  '/konsultasi-mutu': typeof KonsultasiMutuRoute
  '/pelaporan': typeof PelaporanRoute
  '/sistem-informasi': typeof SistemInformasiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dokumen/peraturan-uud': typeof DokumenPeraturanUudRoute
  '/dokumen/pustaka': typeof DokumenPustakaRoute
  '/dokumen/spmi': typeof DokumenSpmiRoute
  '/evaluasi/instrumen': typeof EvaluasiInstrumenRoute
  '/informasi/berita': typeof InformasiBeritaRoute
  '/informasi/detail-berita': typeof InformasiDetailBeritaRoute
  '/spme/spme': typeof SpmeSpmeRoute
  '/tentang/organisasi': typeof TentangOrganisasiRoute
  '/tentang/sambutan-rektor': typeof TentangSambutanRektorRoute
  '/tentang/tupoksi': typeof TentangTupoksiRoute
  '/tentang/visi-misi': typeof TentangVisiMisiRoute
  '/_adminkonten/admin-konten/beranda': typeof AdminkontenAdminKontenBerandaRoute
  '/_adminkonten/admin-konten/kelola-menu': typeof AdminkontenAdminKontenKelolaMenuRoute
  '/_adminkonten/admin-konten/konsultasi-mutu': typeof AdminkontenAdminKontenKonsultasiMutuRoute
  '/_adminkonten/admin-konten/pelaporan': typeof AdminkontenAdminKontenPelaporanRoute
  '/_adminkonten/admin-konten/pengaturan': typeof AdminkontenAdminKontenPengaturanRoute
  '/_adminkonten/admin-konten/sistem-informasi': typeof AdminkontenAdminKontenSistemInformasiRoute
  '/_adminkonten/admin-konten/': typeof AdminkontenAdminKontenIndexRoute
  '/_adminkonten/admin-konten/dokumen/peraturan-uud': typeof AdminkontenAdminKontenDokumenPeraturanUudRoute
  '/_adminkonten/admin-konten/dokumen/pustaka': typeof AdminkontenAdminKontenDokumenPustakaRoute
  '/_adminkonten/admin-konten/dokumen/spmi': typeof AdminkontenAdminKontenDokumenSpmiRoute
  '/_adminkonten/admin-konten/evaluasi/instrumen': typeof AdminkontenAdminKontenEvaluasiInstrumenRoute
  '/_adminkonten/admin-konten/informasi/berita': typeof AdminkontenAdminKontenInformasiBeritaRoute
  '/_adminkonten/admin-konten/informasi/detail-berita': typeof AdminkontenAdminKontenInformasiDetailBeritaRoute
  '/_adminkonten/admin-konten/informasi/pengumuman': typeof AdminkontenAdminKontenInformasiPengumumanRoute
  '/_adminkonten/admin-konten/spme/spme': typeof AdminkontenAdminKontenSpmeSpmeRoute
  '/_adminkonten/admin-konten/tentang/organisasi': typeof AdminkontenAdminKontenTentangOrganisasiRoute
  '/_adminkonten/admin-konten/tentang/sambutan-rektor': typeof AdminkontenAdminKontenTentangSambutanRektorRoute
  '/_adminkonten/admin-konten/tentang/tupoksi': typeof AdminkontenAdminKontenTentangTupoksiRoute
  '/_adminkonten/admin-konten/tentang/visi-misi': typeof AdminkontenAdminKontenTentangVisiMisiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/index1'
    | '/konsultasi-mutu'
    | '/pelaporan'
    | '/sistem-informasi'
    | '/sitemap.xml'
    | '/dokumen/peraturan-uud'
    | '/dokumen/pustaka'
    | '/dokumen/spmi'
    | '/evaluasi/instrumen'
    | '/informasi/berita'
    | '/informasi/detail-berita'
    | '/spme/spme'
    | '/tentang/organisasi'
    | '/tentang/sambutan-rektor'
    | '/tentang/tupoksi'
    | '/tentang/visi-misi'
    | '/admin-konten/beranda'
    | '/admin-konten/kelola-menu'
    | '/admin-konten/konsultasi-mutu'
    | '/admin-konten/pelaporan'
    | '/admin-konten/pengaturan'
    | '/admin-konten/sistem-informasi'
    | '/admin-konten/'
    | '/admin-konten/dokumen/peraturan-uud'
    | '/admin-konten/dokumen/pustaka'
    | '/admin-konten/dokumen/spmi'
    | '/admin-konten/evaluasi/instrumen'
    | '/admin-konten/informasi/berita'
    | '/admin-konten/informasi/detail-berita'
    | '/admin-konten/informasi/pengumuman'
    | '/admin-konten/spme/spme'
    | '/admin-konten/tentang/organisasi'
    | '/admin-konten/tentang/sambutan-rektor'
    | '/admin-konten/tentang/tupoksi'
    | '/admin-konten/tentang/visi-misi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/index1'
    | '/konsultasi-mutu'
    | '/pelaporan'
    | '/sistem-informasi'
    | '/sitemap.xml'
    | '/dokumen/peraturan-uud'
    | '/dokumen/pustaka'
    | '/dokumen/spmi'
    | '/evaluasi/instrumen'
    | '/informasi/berita'
    | '/informasi/detail-berita'
    | '/spme/spme'
    | '/tentang/organisasi'
    | '/tentang/sambutan-rektor'
    | '/tentang/tupoksi'
    | '/tentang/visi-misi'
    | '/admin-konten/beranda'
    | '/admin-konten/kelola-menu'
    | '/admin-konten/konsultasi-mutu'
    | '/admin-konten/pelaporan'
    | '/admin-konten/pengaturan'
    | '/admin-konten/sistem-informasi'
    | '/admin-konten'
    | '/admin-konten/dokumen/peraturan-uud'
    | '/admin-konten/dokumen/pustaka'
    | '/admin-konten/dokumen/spmi'
    | '/admin-konten/evaluasi/instrumen'
    | '/admin-konten/informasi/berita'
    | '/admin-konten/informasi/detail-berita'
    | '/admin-konten/informasi/pengumuman'
    | '/admin-konten/spme/spme'
    | '/admin-konten/tentang/organisasi'
    | '/admin-konten/tentang/sambutan-rektor'
    | '/admin-konten/tentang/tupoksi'
    | '/admin-konten/tentang/visi-misi'
  id:
    | '__root__'
    | '/'
    | '/_adminkonten'
    | '/index1'
    | '/konsultasi-mutu'
    | '/pelaporan'
    | '/sistem-informasi'
    | '/sitemap.xml'
    | '/dokumen/peraturan-uud'
    | '/dokumen/pustaka'
    | '/dokumen/spmi'
    | '/evaluasi/instrumen'
    | '/informasi/berita'
    | '/informasi/detail-berita'
    | '/spme/spme'
    | '/tentang/organisasi'
    | '/tentang/sambutan-rektor'
    | '/tentang/tupoksi'
    | '/tentang/visi-misi'
    | '/_adminkonten/admin-konten/beranda'
    | '/_adminkonten/admin-konten/kelola-menu'
    | '/_adminkonten/admin-konten/konsultasi-mutu'
    | '/_adminkonten/admin-konten/pelaporan'
    | '/_adminkonten/admin-konten/pengaturan'
    | '/_adminkonten/admin-konten/sistem-informasi'
    | '/_adminkonten/admin-konten/'
    | '/_adminkonten/admin-konten/dokumen/peraturan-uud'
    | '/_adminkonten/admin-konten/dokumen/pustaka'
    | '/_adminkonten/admin-konten/dokumen/spmi'
    | '/_adminkonten/admin-konten/evaluasi/instrumen'
    | '/_adminkonten/admin-konten/informasi/berita'
    | '/_adminkonten/admin-konten/informasi/detail-berita'
    | '/_adminkonten/admin-konten/informasi/pengumuman'
    | '/_adminkonten/admin-konten/spme/spme'
    | '/_adminkonten/admin-konten/tentang/organisasi'
    | '/_adminkonten/admin-konten/tentang/sambutan-rektor'
    | '/_adminkonten/admin-konten/tentang/tupoksi'
    | '/_adminkonten/admin-konten/tentang/visi-misi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminkontenRoute: typeof AdminkontenRouteWithChildren
  Index1Route: typeof Index1Route
  KonsultasiMutuRoute: typeof KonsultasiMutuRoute
  PelaporanRoute: typeof PelaporanRoute
  SistemInformasiRoute: typeof SistemInformasiRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DokumenPeraturanUudRoute: typeof DokumenPeraturanUudRoute
  DokumenPustakaRoute: typeof DokumenPustakaRoute
  DokumenSpmiRoute: typeof DokumenSpmiRoute
  EvaluasiInstrumenRoute: typeof EvaluasiInstrumenRoute
  InformasiBeritaRoute: typeof InformasiBeritaRoute
  InformasiDetailBeritaRoute: typeof InformasiDetailBeritaRoute
  SpmeSpmeRoute: typeof SpmeSpmeRoute
  TentangOrganisasiRoute: typeof TentangOrganisasiRoute
  TentangSambutanRektorRoute: typeof TentangSambutanRektorRoute
  TentangTupoksiRoute: typeof TentangTupoksiRoute
  TentangVisiMisiRoute: typeof TentangVisiMisiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistem-informasi': {
      id: '/sistem-informasi'
      path: '/sistem-informasi'
      fullPath: '/sistem-informasi'
      preLoaderRoute: typeof SistemInformasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelaporan': {
      id: '/pelaporan'
      path: '/pelaporan'
      fullPath: '/pelaporan'
      preLoaderRoute: typeof PelaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konsultasi-mutu': {
      id: '/konsultasi-mutu'
      path: '/konsultasi-mutu'
      fullPath: '/konsultasi-mutu'
      preLoaderRoute: typeof KonsultasiMutuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index1': {
      id: '/index1'
      path: '/index1'
      fullPath: '/index1'
      preLoaderRoute: typeof Index1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminkonten': {
      id: '/_adminkonten'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminkontenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang/visi-misi': {
      id: '/tentang/visi-misi'
      path: '/tentang/visi-misi'
      fullPath: '/tentang/visi-misi'
      preLoaderRoute: typeof TentangVisiMisiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang/tupoksi': {
      id: '/tentang/tupoksi'
      path: '/tentang/tupoksi'
      fullPath: '/tentang/tupoksi'
      preLoaderRoute: typeof TentangTupoksiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang/sambutan-rektor': {
      id: '/tentang/sambutan-rektor'
      path: '/tentang/sambutan-rektor'
      fullPath: '/tentang/sambutan-rektor'
      preLoaderRoute: typeof TentangSambutanRektorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang/organisasi': {
      id: '/tentang/organisasi'
      path: '/tentang/organisasi'
      fullPath: '/tentang/organisasi'
      preLoaderRoute: typeof TentangOrganisasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spme/spme': {
      id: '/spme/spme'
      path: '/spme/spme'
      fullPath: '/spme/spme'
      preLoaderRoute: typeof SpmeSpmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi/detail-berita': {
      id: '/informasi/detail-berita'
      path: '/informasi/detail-berita'
      fullPath: '/informasi/detail-berita'
      preLoaderRoute: typeof InformasiDetailBeritaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi/berita': {
      id: '/informasi/berita'
      path: '/informasi/berita'
      fullPath: '/informasi/berita'
      preLoaderRoute: typeof InformasiBeritaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluasi/instrumen': {
      id: '/evaluasi/instrumen'
      path: '/evaluasi/instrumen'
      fullPath: '/evaluasi/instrumen'
      preLoaderRoute: typeof EvaluasiInstrumenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumen/spmi': {
      id: '/dokumen/spmi'
      path: '/dokumen/spmi'
      fullPath: '/dokumen/spmi'
      preLoaderRoute: typeof DokumenSpmiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumen/pustaka': {
      id: '/dokumen/pustaka'
      path: '/dokumen/pustaka'
      fullPath: '/dokumen/pustaka'
      preLoaderRoute: typeof DokumenPustakaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumen/peraturan-uud': {
      id: '/dokumen/peraturan-uud'
      path: '/dokumen/peraturan-uud'
      fullPath: '/dokumen/peraturan-uud'
      preLoaderRoute: typeof DokumenPeraturanUudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminkonten/admin-konten/': {
      id: '/_adminkonten/admin-konten/'
      path: '/admin-konten'
      fullPath: '/admin-konten/'
      preLoaderRoute: typeof AdminkontenAdminKontenIndexRouteImport
      parentRoute: typeof AdminkontenRoute
    }
    '/_adminkonten/admin-konten/sistem-informasi': {
      id: '/_adminkonten/admin-konten/sistem-informasi'
      path: '/admin-konten/sistem-informasi'
      fullPath: '/admin-konten/sistem-informasi'
      preLoaderRoute: typeof AdminkontenAdminKontenSistemInformasiRouteImport
      parentRoute: typeof AdminkontenRoute
    }
    '/_adminkonten/admin-konten/pengaturan': {
      id: '/_adminkonten/admin-konten/pengaturan'
      path: '/admin-konten/pengaturan'
      fullPath: '/admin-konten/pengaturan'
      preLoaderRoute: typeof AdminkontenAdminKontenPengaturanRouteImport
      parentRoute: typeof AdminkontenRoute
    }
    '/_adminkonten/admin-konten/pelaporan': {
      id: '/_adminkonten/admin-konten/pelaporan'
      path: '/admin-konten/pelaporan'
      fullPath: '/admin-konten/pelaporan'
      preLoaderRoute: typeof AdminkontenAdminKontenPelaporanRouteImport
      parentRoute: typeof AdminkontenRoute
    }
    '/_adminkonten/admin-konten/konsultasi-mutu': {
      id: '/_adminkonten/admin-konten/konsultasi-mutu'
      path: '/admin-konten/konsultasi-mutu'
      fullPath: '/admin-konten/konsultasi-mutu'
      preLoaderRoute: typeof AdminkontenAdminKontenKonsultasiMutuRouteImport
      parentRoute: typeof AdminkontenRoute
    }
    '/_adminkonten/admin-konten/kelola-menu': {
      id: '/_adminkonten/admin-konten/kelola-menu'
      path: '/admin-konten/kelola-menu'
      fullPath: '/admin-konten/kelola-menu'
      preLoaderRoute: typeof AdminkontenAdminKontenKelolaMenuRouteImport
      parentRoute: typeof AdminkontenRoute
    }
    '/_adminkonten/admin-konten/beranda': {
      id: '/_adminkonten/admin-konten/beranda'
      path: '/admin-konten/beranda'
      fullPath: '/admin-konten/beranda'
      preLoaderRoute: typeof AdminkontenAdminKontenBerandaRouteImport
      parentRoute: typeof AdminkontenRoute
    }
    '/_adminkonten/admin-konten/tentang/visi-misi': {
      id: '/_adminkonten/admin-konten/tentang/visi-misi'
      path: '/admin-konten/tentang/visi-misi'
      fullPath: '/admin-konten/tentang/visi-misi'
      preLoaderRoute: typeof AdminkontenAdminKontenTentangVisiMisiRouteImport
      parentRoute: typeof AdminkontenRoute
    }
    '/_adminkonten/admin-konten/tentang/tupoksi': {
      id: '/_adminkonten/admin-konten/tentang/tupoksi'
      path: '/admin-konten/tentang/tupoksi'
      fullPath: '/admin-konten/tentang/tupoksi'
      preLoaderRoute: typeof AdminkontenAdminKontenTentangTupoksiRouteImport
      parentRoute: typeof AdminkontenRoute
    }
    '/_adminkonten/admin-konten/tentang/sambutan-rektor': {
      id: '/_adminkonten/admin-konten/tentang/sambutan-rektor'
      path: '/admin-konten/tentang/sambutan-rektor'
      fullPath: '/admin-konten/tentang/sambutan-rektor'
      preLoaderRoute: typeof AdminkontenAdminKontenTentangSambutanRektorRouteImport
      parentRoute: typeof AdminkontenRoute
    }
    '/_adminkonten/admin-konten/tentang/organisasi': {
      id: '/_adminkonten/admin-konten/tentang/organisasi'
      path: '/admin-konten/tentang/organisasi'
      fullPath: '/admin-konten/tentang/organisasi'
      preLoaderRoute: typeof AdminkontenAdminKontenTentangOrganisasiRouteImport
      parentRoute: typeof AdminkontenRoute
    }
    '/_adminkonten/admin-konten/spme/spme': {
      id: '/_adminkonten/admin-konten/spme/spme'
      path: '/admin-konten/spme/spme'
      fullPath: '/admin-konten/spme/spme'
      preLoaderRoute: typeof AdminkontenAdminKontenSpmeSpmeRouteImport
      parentRoute: typeof AdminkontenRoute
    }
    '/_adminkonten/admin-konten/informasi/pengumuman': {
      id: '/_adminkonten/admin-konten/informasi/pengumuman'
      path: '/admin-konten/informasi/pengumuman'
      fullPath: '/admin-konten/informasi/pengumuman'
      preLoaderRoute: typeof AdminkontenAdminKontenInformasiPengumumanRouteImport
      parentRoute: typeof AdminkontenRoute
    }
    '/_adminkonten/admin-konten/informasi/detail-berita': {
      id: '/_adminkonten/admin-konten/informasi/detail-berita'
      path: '/admin-konten/informasi/detail-berita'
      fullPath: '/admin-konten/informasi/detail-berita'
      preLoaderRoute: typeof AdminkontenAdminKontenInformasiDetailBeritaRouteImport
      parentRoute: typeof AdminkontenRoute
    }
    '/_adminkonten/admin-konten/informasi/berita': {
      id: '/_adminkonten/admin-konten/informasi/berita'
      path: '/admin-konten/informasi/berita'
      fullPath: '/admin-konten/informasi/berita'
      preLoaderRoute: typeof AdminkontenAdminKontenInformasiBeritaRouteImport
      parentRoute: typeof AdminkontenRoute
    }
    '/_adminkonten/admin-konten/evaluasi/instrumen': {
      id: '/_adminkonten/admin-konten/evaluasi/instrumen'
      path: '/admin-konten/evaluasi/instrumen'
      fullPath: '/admin-konten/evaluasi/instrumen'
      preLoaderRoute: typeof AdminkontenAdminKontenEvaluasiInstrumenRouteImport
      parentRoute: typeof AdminkontenRoute
    }
    '/_adminkonten/admin-konten/dokumen/spmi': {
      id: '/_adminkonten/admin-konten/dokumen/spmi'
      path: '/admin-konten/dokumen/spmi'
      fullPath: '/admin-konten/dokumen/spmi'
      preLoaderRoute: typeof AdminkontenAdminKontenDokumenSpmiRouteImport
      parentRoute: typeof AdminkontenRoute
    }
    '/_adminkonten/admin-konten/dokumen/pustaka': {
      id: '/_adminkonten/admin-konten/dokumen/pustaka'
      path: '/admin-konten/dokumen/pustaka'
      fullPath: '/admin-konten/dokumen/pustaka'
      preLoaderRoute: typeof AdminkontenAdminKontenDokumenPustakaRouteImport
      parentRoute: typeof AdminkontenRoute
    }
    '/_adminkonten/admin-konten/dokumen/peraturan-uud': {
      id: '/_adminkonten/admin-konten/dokumen/peraturan-uud'
      path: '/admin-konten/dokumen/peraturan-uud'
      fullPath: '/admin-konten/dokumen/peraturan-uud'
      preLoaderRoute: typeof AdminkontenAdminKontenDokumenPeraturanUudRouteImport
      parentRoute: typeof AdminkontenRoute
    }
  }
}

interface AdminkontenRouteChildren {
  AdminkontenAdminKontenBerandaRoute: typeof AdminkontenAdminKontenBerandaRoute
  AdminkontenAdminKontenKelolaMenuRoute: typeof AdminkontenAdminKontenKelolaMenuRoute
  AdminkontenAdminKontenKonsultasiMutuRoute: typeof AdminkontenAdminKontenKonsultasiMutuRoute
  AdminkontenAdminKontenPelaporanRoute: typeof AdminkontenAdminKontenPelaporanRoute
  AdminkontenAdminKontenPengaturanRoute: typeof AdminkontenAdminKontenPengaturanRoute
  AdminkontenAdminKontenSistemInformasiRoute: typeof AdminkontenAdminKontenSistemInformasiRoute
  AdminkontenAdminKontenIndexRoute: typeof AdminkontenAdminKontenIndexRoute
  AdminkontenAdminKontenDokumenPeraturanUudRoute: typeof AdminkontenAdminKontenDokumenPeraturanUudRoute
  AdminkontenAdminKontenDokumenPustakaRoute: typeof AdminkontenAdminKontenDokumenPustakaRoute
  AdminkontenAdminKontenDokumenSpmiRoute: typeof AdminkontenAdminKontenDokumenSpmiRoute
  AdminkontenAdminKontenEvaluasiInstrumenRoute: typeof AdminkontenAdminKontenEvaluasiInstrumenRoute
  AdminkontenAdminKontenInformasiBeritaRoute: typeof AdminkontenAdminKontenInformasiBeritaRoute
  AdminkontenAdminKontenInformasiDetailBeritaRoute: typeof AdminkontenAdminKontenInformasiDetailBeritaRoute
  AdminkontenAdminKontenInformasiPengumumanRoute: typeof AdminkontenAdminKontenInformasiPengumumanRoute
  AdminkontenAdminKontenSpmeSpmeRoute: typeof AdminkontenAdminKontenSpmeSpmeRoute
  AdminkontenAdminKontenTentangOrganisasiRoute: typeof AdminkontenAdminKontenTentangOrganisasiRoute
  AdminkontenAdminKontenTentangSambutanRektorRoute: typeof AdminkontenAdminKontenTentangSambutanRektorRoute
  AdminkontenAdminKontenTentangTupoksiRoute: typeof AdminkontenAdminKontenTentangTupoksiRoute
  AdminkontenAdminKontenTentangVisiMisiRoute: typeof AdminkontenAdminKontenTentangVisiMisiRoute
}

const AdminkontenRouteChildren: AdminkontenRouteChildren = {
  AdminkontenAdminKontenBerandaRoute: AdminkontenAdminKontenBerandaRoute,
  AdminkontenAdminKontenKelolaMenuRoute: AdminkontenAdminKontenKelolaMenuRoute,
  AdminkontenAdminKontenKonsultasiMutuRoute:
    AdminkontenAdminKontenKonsultasiMutuRoute,
  AdminkontenAdminKontenPelaporanRoute: AdminkontenAdminKontenPelaporanRoute,
  AdminkontenAdminKontenPengaturanRoute: AdminkontenAdminKontenPengaturanRoute,
  AdminkontenAdminKontenSistemInformasiRoute:
    AdminkontenAdminKontenSistemInformasiRoute,
  AdminkontenAdminKontenIndexRoute: AdminkontenAdminKontenIndexRoute,
  AdminkontenAdminKontenDokumenPeraturanUudRoute:
    AdminkontenAdminKontenDokumenPeraturanUudRoute,
  AdminkontenAdminKontenDokumenPustakaRoute:
    AdminkontenAdminKontenDokumenPustakaRoute,
  AdminkontenAdminKontenDokumenSpmiRoute:
    AdminkontenAdminKontenDokumenSpmiRoute,
  AdminkontenAdminKontenEvaluasiInstrumenRoute:
    AdminkontenAdminKontenEvaluasiInstrumenRoute,
  AdminkontenAdminKontenInformasiBeritaRoute:
    AdminkontenAdminKontenInformasiBeritaRoute,
  AdminkontenAdminKontenInformasiDetailBeritaRoute:
    AdminkontenAdminKontenInformasiDetailBeritaRoute,
  AdminkontenAdminKontenInformasiPengumumanRoute:
    AdminkontenAdminKontenInformasiPengumumanRoute,
  AdminkontenAdminKontenSpmeSpmeRoute: AdminkontenAdminKontenSpmeSpmeRoute,
  AdminkontenAdminKontenTentangOrganisasiRoute:
    AdminkontenAdminKontenTentangOrganisasiRoute,
  AdminkontenAdminKontenTentangSambutanRektorRoute:
    AdminkontenAdminKontenTentangSambutanRektorRoute,
  AdminkontenAdminKontenTentangTupoksiRoute:
    AdminkontenAdminKontenTentangTupoksiRoute,
  AdminkontenAdminKontenTentangVisiMisiRoute:
    AdminkontenAdminKontenTentangVisiMisiRoute,
}

const AdminkontenRouteWithChildren = AdminkontenRoute._addFileChildren(
  AdminkontenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminkontenRoute: AdminkontenRouteWithChildren,
  Index1Route: Index1Route,
  KonsultasiMutuRoute: KonsultasiMutuRoute,
  PelaporanRoute: PelaporanRoute,
  SistemInformasiRoute: SistemInformasiRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DokumenPeraturanUudRoute: DokumenPeraturanUudRoute,
  DokumenPustakaRoute: DokumenPustakaRoute,
  DokumenSpmiRoute: DokumenSpmiRoute,
  EvaluasiInstrumenRoute: EvaluasiInstrumenRoute,
  InformasiBeritaRoute: InformasiBeritaRoute,
  InformasiDetailBeritaRoute: InformasiDetailBeritaRoute,
  SpmeSpmeRoute: SpmeSpmeRoute,
  TentangOrganisasiRoute: TentangOrganisasiRoute,
  TentangSambutanRektorRoute: TentangSambutanRektorRoute,
  TentangTupoksiRoute: TentangTupoksiRoute,
  TentangVisiMisiRoute: TentangVisiMisiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
